baseURL = 'https://blog.webstra.dev/'
languageCode = 'en-us'
title = 'WebstraDev Blog'
publishDir = "docs"

theme = "anatole"

[params]
  title = "webstradev"
  description = "Erik Westra"
  author = "Erik Westra (webstradev)"
  profilePicture = "images/profile.jpg"
  favicon = "favicons/"
  keywords = ""
  contentratio = 0.75
  postSectionName = "blog"
  fullPostContent = true
  enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Recent"
    identifier = "home"
    weight = 100
    url = "/"
  [[menu.main]]
    name = "All Posts"
    identifier = "blog"
    weight = 200
    url = "/posts"
  
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://link.webstra.dev/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://git.webstra.dev/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://x.webstra.dev/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:erik@webstra.dev"
